name: rosa
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2024.9.24
  - geos=3.13.0
  - grpcio=1.62.2
  - importlib-metadata=8.5.0
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libprotobuf=4.25.3
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markdown=3.6
  - markupsafe=3.0.2
  - ncurses=6.4
  - numpy=2.1.2
  - openssl=3.3.2
  - packaging=24.1
  - pip=24.2
  - python=3.10.15
  - python_abi=3.10
  - re2=2022.04.01
  - readline=8.2
  - setuptools=75.1.0
  - shapely=2.0.6
  - six=1.16.0
  - sqlite=3.45.3
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.14
  - werkzeug=3.1.2
  - wheel=0.44.0
  - xz=5.4.6
  - zipp=3.20.2
  - zlib=1.2.13
  - pandas
  - imageio
  - plotly
  - gym
  - pytorch
  - pip:
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - fsspec==2024.10.0
      - geopandas==1.0.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - kornia==0.7.4
      - kornia-rs==0.1.7
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.3.6
      - protobuf==3.20.3
      - psutil==6.1.0
      - pyogrio==0.10.0
      - pyparsing==3.2.0
      - pyproj==3.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - stable-baselines3
      - sympy==1.13.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.66.6
      - traci
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wandb==0.18.5
      - sumolib
